#!/usr/bin/env bash

set -e

if command -v aws &> /dev/null; then
    echo "aws is already installed"
else
    echo "Install dependencies"
{% if yadm.distro_family == "debian" %}
    sudo apt update -y
    sudo apt install -y curl unzip
{% endif %}
{% if yadm.distro_family == "arch" %}
    sudo pacman -Syu --noconfirm
    sudo pacman -S --noconfirm --needed curl unzip
{% endif %}

    echo "Install AWS cli"
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
    cd /tmp || exit 1
    unzip awscliv2.zip
    sudo ./aws/install
    rm -rf ./awscliv2.zip ./aws
fi

