#!/usr/bin/env bash

set -e

if command -v docker &> /dev/null; then
    echo "docker is already installed"
else
{% if yadm.distro_family == "debian" %}
    echo "Install dependencies"
    sudo apt update -y
    sudo apt install -y curl unzip apt-transport-https ca-certificates software-properties-common

    # repo/gpg key
    echo "create gpg key"
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
        | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    # install packages
    echo "install docker"
    sudo apt install -y docker-ce docker-ce-cli docker-compose-plugin
{% endif %}
{% if yadm.distro_family == "arch" %}
    echo "install docker"
    sudo pacman -Syu --noconfirm
    sudo pacman -S --noconfirm --needed docker docker-compose
{% endif %}
    # add user to docker group to be able to run without sudo
    echo "Adding '${USER}' to docker group"
    sudo groupadd -f docker
    sudo usermod -aG docker "$USER"
fi
