#!/usr/bin/env bash

if command -v nvim &> /dev/null; then
    echo "neovim is already installed"
else
{% if yadm.distro_family == "debian" %}
    echo "Add neovim ppa"
    sudo add-apt-repository -y ppa:neovim-ppa/unstable

    echo "Installing neovim"
    sudo apt update -y
    sudo apt install -y neovim python3-pynvim xclip
{% endif %}
{% if yadm.distro_family == "arch" %}
    sudo pacman -Syu --noconfirm
    sudo pacman -S --noconfirm --needed neovim python-pynvim xclip
{% endif %}
fi
