#!/usr/bin/env bash

set -e

FONT_NAME="Iosevka"
FONTS_DIR="$HOME/.local/share/fonts"
TARGET_DIR="${FONTS_DIR}/${FONT_NAME}_NerdFont"

if [ -d "$TARGET_DIR" ]; then
    echo "$FONT_NAME Nerd Font is already installed."
else
{% if yadm.distro_family == "debian" %}
    # install dependencies
    sudo apt update -y
    sudo apt install -y wget
{% endif %}
{% if yadm.distro_family == "arch" %}
    sudo pacman -Syu --noconfirm
    sudo pacman -S --noconfirm --needed wget
{% endif %}

    # download from github releases
    WORKING_DIR=$(mktemp -d)
    NERDFONT_VERSION="3.0.2"
    NERDFONT_URL="https://github.com/ryanoasis/nerd-fonts/releases/download/v$NERDFONT_VERSION/$FONT_NAME.zip"
    echo "Downloading $FONT_NAME Nerd Font..."
    
    # extract and install
    wget -P "$WORKING_DIR" "$NERDFONT_URL"
    unzip "$WORKING_DIR/$FONT_NAME.zip" -d "$WORKING_DIR"
    rm "$WORKING_DIR/$FONT_NAME.zip"
    mkdir -p "$TARGET_DIR"
    cp "$WORKING_DIR/$FONT_NAME"* "$TARGET_DIR/"
    fc-cache -f
    echo "$FONT_NAME Nerd Font has been installed."

    # cleanup
    rm -rf "$WORKING_DIR"
fi
