#!/usr/bin/env bash

set -e

FONT_NAMES=("Iosevka" "IBMPlexMono" "JetBrainsMono")
FONTS_DIR="$HOME/.local/share/fonts"
DEPS_INSTALLED=false

function install_dependencies() {
    if "$DEPS_INSTALLED"; then
	return
    fi
    echo "Install dependencies"
{% if yadm.distro_family == "debian" %}
    sudo apt update -y
    sudo apt install -y wget
{% endif %}
{% if yadm.distro_family == "arch" %}
    sudo pacman -Syu --noconfirm
    sudo pacman -S --noconfirm --needed wget
{% endif %}
    DEPS_INSTALLED=true
}

for FONT_NAME in "${FONT_NAMES[@]}"; do
    TARGET_DIR="${FONTS_DIR}/NerdFonts/${FONT_NAME}"
    
    echo
    if [ -d "$TARGET_DIR" ]; then
        echo "$FONT_NAME Nerd Font is already installed."
    else
	install_dependencies

	echo "Installing $FONT_NAME Nerd Font..."
        # download from github releases
        WORKING_DIR=$(mktemp -d)
        NERDFONT_VERSION="3.0.2"
        NERDFONT_URL="https://github.com/ryanoasis/nerd-fonts/releases/download/v$NERDFONT_VERSION/$FONT_NAME.zip"
        echo "Downloading $FONT_NAME Nerd Font..."
        
        # extract and install
        wget -P "$WORKING_DIR" "$NERDFONT_URL"
        unzip "$WORKING_DIR/$FONT_NAME.zip" -d "$WORKING_DIR"
        rm "$WORKING_DIR/$FONT_NAME.zip"
        mkdir -p "$TARGET_DIR"
        cp "$WORKING_DIR"/*.ttf "$TARGET_DIR/"
        fc-cache -f
        echo "$FONT_NAME Nerd Font has been installed."
    
        # cleanup
        rm -rf "$WORKING_DIR"
    fi
done
