#!/usr/bin/env bash

if command -v yadm &> /dev/null; then
    echo "yadm is already installed"
else
    echo "Installing yadm"
{% if yadm.distro_family == "debian" %}
    sudo apt update
    sudo apt install -y yadm
{% endif %}
{% if yadm.distro_family == "arch" %}
    sudo pacman -Syu --noconfirm
    sudo pacman -S --noconfirm --needed yadm
{% endif %}
fi

CURRENT_ORIGIN_URL=$(yadm remote get-url origin)
echo "yadm repo origin is $CURRENT_ORIGIN_URL"

ORIGIN_URL="git@github.com:js-beaulieu/dotfiles-unix.git"
if [ "$CURRENT_ORIGIN_URL" != "$ORIGIN_URL" ]; then
    echo "updating yadm repo origin to $ORIGIN_URL"
    yadm remote set-url origin "$ORIGIN_URL"
fi
