#!/usr/bin/env bash

if command -v yadm &> /dev/null; then
    echo "yadm is already installed"
else
    echo "Installing yadm"
    sudo apt update
    sudo apt install -y yadm
fi

CURRENT_ORIGIN_URL=$(yadm remote get-url origin)
echo "yadm repo origin is $CURRENT_ORIGIN_URL"

ORIGIN_URL="git@github.com:js-beaulieu/dotfiles-unix.git"
if [ "$CURRENT_ORIGIN_URL" != "$ORIGIN_URL" ]; then
    echo "updating yadm repo origin to $ORIGIN_URL"
    yadm remote set-url origin "$ORIGIN_URL"
fi
