#!/usr/bin/env bash

set -e

if command -v zsh &> /dev/null; then
    echo "zsh is already installed"
else
    echo "Installing zsh"
{% if yadm.distro_family == "debian" %}
    sudo apt update -y
    sudo apt install -y zsh
{% endif %}
{% if yadm.distro_family == "arch" %}
    sudo pacman -Syu --noconfirm
    sudo pacman -S --noconfirm --needed zsh
{% endif %}
fi

ln -sf "$HOME/.config/zsh/.zshenv" "$HOME/.zshenv"
echo "you should run 'chsh -s $(which zsh)' to use zsh by default"
